pipeline {
    agent any
    
    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        COMPOSE_DIR = "Poc/Poc/src/main/resources"
    }

    stages {

        stage('Initialisation Workspace') {
            steps {
                echo 'Récupération sécurisée du fichier .env depuis Jenkins...'
                // Jenkins extrait le fichier secret et crée un chemin temporaire ($ENV_FILE)
                withCredentials([file(credentialsId: 'medhead-env-file', variable: 'ENV_FILE')]) {
                    // On copie ce fichier secret vers le dossier de ressources
                    sh "cp \$ENV_FILE ${COMPOSE_DIR}/.env"
                }
                
                dir("${COMPOSE_DIR}") {
                    sh "ls -la .env && echo 'Succès : Fichier .env injecté.'"
                }
            }
        }

        stage('Nettoyage & Préparation') {
            steps {
                echo 'Redémarrage des services applicatifs...'
                // On ne stoppe que l'app et la db pour garder SonarQube "chaud" (plus rapide)
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml stop app db"
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml rm -f app db"
                // up -d s'assure que tout tourne sans réinitialiser Sonar s'il est déjà là
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml up -d db app sonarqube newman-db-cleaner"
            }
        }

        stage('Compilation') {
            steps {
                echo 'Compilation du projet avec le Maven de Jenkins...'
                // On se déplace dans le dossier contenant le fichier pom.xml (Poc/Poc)
                dir("Poc/Poc") {
                    sh "mvn clean compile"
                }
            }
        }

        stage('Lancement Application') {
            steps {
                echo 'Démarrage avec lecture directe du fichier .env par Docker...'
                dir("${COMPOSE_DIR}") {
                    sh "docker-compose --env-file .env up -d app"
                }

                echo 'Attente de stabilisation (30s)...'
                sleep 30
            }
        }

        stage('Analyse (SonarQube)') {
            steps {
                echo 'Lancement du scan...'
                sh """
                    docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm \
                    sonar-scanner \
                    -Dsonar.projectKey=MedHead_PoC \
                    -Dsonar.projectName=MedHead_PoC_System \
                    -Dsonar.host.url=http://sonarqube-poc:9000 \
                    -Dsonar.login=admin \
                    -Dsonar.password=admin \
                    -Dsonar.sources=. \
                    -Dsonar.java.binaries=. \
                    -Dsonar.exclusions=**/target/**,**/*.env
                """
            }
        }


        stage('Data pour tests') {
            steps {
                echo 'Injection manuelle des fichiers et lancement des tests...'
                dir("${COMPOSE_DIR}") {

                    // 1. INJECTION DE IMPORT.SQL (Pour remplir la base vide)
                    echo 'Importation des données initiales (import.sql)...'
                    sh "docker cp sql-init/import.sql newman-db-cleaner:/tmp/import.sql"
                    sh "docker exec newman-db-cleaner sh -c 'mariadb -h db -u root -pexample poc_db < /tmp/import.sql'"

                    // 2. INJECTION DE CLEAN_DB.SQL (Pour préparer les cas d'erreur Newman)
                    echo 'Préparation des scénarios de tests (clean_db.sql)...'
                    sh "docker cp api_tests_newman/clean_db.sql newman-db-cleaner:/tmp/clean_db.sql"
                    sh "docker exec newman-db-cleaner sh -c 'mariadb -h db -u root -pexample poc_db < /tmp/clean_db.sql'"
                    
                    sleep 10 // Petit délai pour s'assurer que le cleaner a fini

                }
            }
        }

        /*/ Newman fonctionne correctement commenter pour l'instant pour se concentrer sur les E2E
        stage('Tests API (Newman)') {
            steps {
                echo 'Injection manuelle des fichiers et lancement des tests...'
                dir("${COMPOSE_DIR}") {

                    // 1. Préparation de Newman (Injection des tests JSON)
                    // On crée le conteneur sans le lancer pour y copier les fichiers
                    sh "docker-compose create newman"
                    sh "docker cp api_tests_newman/collection.json newman-api-tests:/etc/newman/collection.json"
                    sh "docker cp api_tests_newman/env.json newman-api-tests:/etc/newman/env.json"
                    
                    // 2. Exécution de Newman
                    // -a permet d'afficher la sortie dans la console Jenkins
                    sh "docker start -a newman-api-tests"
                }
            }
        }
        */


        stage('Tests E2E (Selenium)') {
            steps {
                echo 'Lancement des scénarios...'

                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    // Montage sur /tmp/output pour ne PAS toucher au dossier /app du code
                    sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm --build -v \$(pwd):/tmp/output e2e-reservation node E2E_connexion_clicSpecialite_Selection_SaisieAdresse_reservation.js"
                }

                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm --build-v \$(pwd):/tmp/output e2e-reservation node E2E_connexion_RechercheSpecialite_clicSpecialite_Selection_ClicGPS_reservation.js"
                }
            }
        }
    }
    post {
        always {
            echo 'Archivage des rapports et nettoyage...'
            // 1 Récupère toutes les captures d'écran (.png) générées pendant les tests
            archiveArtifacts artifacts: '*.png', allowEmptyArchive: true
            // 2. On stoppe d'abord (Docker a besoin du .env pour identifier les services)
            sleep 10 // Petit délai pour s'assurer que tout est bien fini avant le stop

            sleep 120 // a enlver pour debug

            sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml stop app db newman-db-cleaner"
            // 3. On supprime le secret ensuite
            sh "rm -f ${COMPOSE_DIR}/.env"
        }
    }
}