pipeline {
    agent any
    
    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        COMPOSE_DIR = "Poc/Poc/src/main/resources"
    }

    stages {
        stage('Initialisation Workspace') {
            steps {
                echo 'Injection des secrets locaux...'
                sh "cp /tmp/.env ${COMPOSE_DIR}/.env"
            }
        }

        stage('Nettoyage & Préparation') {
            steps {
                echo 'Redémarrage des services applicatifs...'
                // On ne stoppe que l'app et la db pour garder SonarQube "chaud" (plus rapide)
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml stop app db"
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml rm -f app db"
                // up -d s'assure que tout tourne sans réinitialiser Sonar s'il est déjà là
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml up -d db app sonarqube"
            }
        }

        stage('Analyse SonarQube') {
            steps {
                echo 'Attente de stabilisation de SonarQube (30s)...'
                sleep 30
                echo 'Lancement du scan SonarQube (Version 5 + Compatibilité)...'
                sh """
                docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm \
                  -e SONAR_SCANNER_OPTS="-Dsonar.scanner.skipJreProvisioning=true" \
                  sonar-scanner \
                  -Dsonar.projectKey=MedHead_PoC \
                  -Dsonar.projectName=MedHead_PoC_System \
                  -Dsonar.host.url=http://sonarqube-poc:9000 \
                  -Dsonar.token=sqa_8019e09d17208d245451f28e2025700839e9a3b9 \
                  -Dsonar.sources=Poc/Poc/src/main/java \
                  -Dsonar.java.binaries=Poc/Poc/target/classes \
                  -Dsonar.scanner.force-deprecated-api-usage=true \
                  -Dsonar.exclusions=**/*.env
                """
            }
        }

        stage('Tests API (Newman)') {
            steps {
                echo 'Nettoyage DB et lancement Newman...'
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm newman-db-cleaner"
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm newman"
            }
        }

        stage('Tests E2E') {
            steps {
                echo 'Lancement des scénarios Selenium...'
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm e2e-reservation"
                sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml run --rm e2e-autre-test"
            }
        }
    }

    post {
        always {
            echo 'Nettoyage final...'
            // 1. On stoppe d'abord (Docker a besoin du .env pour identifier les services)
            sh "docker-compose -f ${COMPOSE_DIR}/compose.yaml stop app db"
            // 2. On supprime le secret ensuite
            sh "rm -f ${COMPOSE_DIR}/.env"
        }
    }
}